### ISSUE TITLE
IndexError on login/dash load

### ISSUE THREAD

**Issue by TheFantasticLoki** [RealistikOsu/RealistikPanel#65]
Hey I'm trying to get your panel working for our server and after many hours of troubleshooting just trying to get it to run on my dev vm I'm getting this error on login that I don't know how to handle. Throws 500 error on browser and this in the terminal:
ERROR in app: Exception on /dash/ [GET]
Traceback (most recent call last):
  File "/home/kawata/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kawata/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kawata/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kawata/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kawata/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kawata/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 46, in dash
    return render_template("dash.html", title="Dashboard", session=session, data=DashData(), plays=RecentPlays(), config=UserConfig, Graph=DashActData(), MostPlayed=GetMostPlayed())
  File "/var/www/osu.ppy.sh/functions.py", line 136, in DashData
    Alert = Alert[0][0]
IndexError: list index out of range

**Comment by RealistikDash** [comment]
Hey, thanks for using RealistikPanel! I believe this issue comes from the minor differences with every Ripple based instance, with every single one having its own small ways of doing things.

This specific error originates from RealistikPanel not being able to find within the table `system_settings` a row where the column name is equal to  `website_home_alert'"`. This is pretty much the way to set alerts within Hanayo and I have not yet implemented an edge case for when it is not present.

A simple workaround for this would be simply inserting a row into `system_settings` with the name of `website_home_alert'"` and everything else empty.
